env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"

task:
  name: Build
  timeout_in: 2h
  persistent_worker:
    labels:
      name: instance-1

  sync_scripts:
     - mkdir Cherish
     - cd Cherish
     - repo init --no-repo-verify --depth=1 -u https://github.com/CherishOS/android_manifest.git -b eleven -g default,-device,-mips,-darwin,-notdefault
     - git clone --depth=1 https://github.com/adrian-8901/.repo-local_manifest.git .repo/local_manifests
     - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
  
  build_scripts: 
     - . build/envsetup.sh
     - lunch cherish_umi-userdebug
     - mka bacon -j8 


 
